### ISSUE TITLE
Teleop is weird

### ISSUE THREAD

**Issue by OriginalAndCreativeName** [Centennial-FTC-Robotics/Exponential2019-2020#1]
Quoting Keertik: 
"
the teleop program that expo programmers have installed onto the phone is a bit weird
like right stick up moves the robot backwards
"

Needed by Friday for outreach

**Comment by keertikbacon** [comment]
I think it's a config problem, cause when I made one for the bot yesterday I forgot the motors were plugged in a weird order. Just use another config and make sure the motor names match those in the program.
